---
title: "Lab1Checkbox4"
author: "Lucas Barros Rocha"
date: "29 de maio de 2017"
output: html_document
---

```{r setup, include=FALSE}
library("ggplot2")
library("dplyr")
library("tidyr")
library("readr")

dados = read_csv(file = "series.csv")
```

```{r}

media.temporada.s <- dados %>%
  filter(series_name== "Sherlock") %>%
  group_by(season) %>%
  summarise(media = mean(UserRating))

ggplot(data = media.temporada.s, aes(x=season, y=media, fill = season)) + geom_bar(stat = "identity") + ggtitle("Sherlock")

```

```{r}

media.temporada.g <- dados %>%
  filter(series_name== "Gotham") %>%
  group_by(season) %>%
  summarise(media = mean(UserRating))

ggplot(data = media.temporada.g, aes(x=season, y=media, fill = season)) + geom_bar(stat = "identity") + ggtitle("Gotham")

```

```{r}

media.temporada.b <- dados %>%
  filter(series_name== "Black Mirror") %>%
  group_by(season) %>%
  summarise(media = mean(UserRating))

ggplot(data = media.temporada.b, aes(x=season, y=media, fill = season)) + geom_bar(stat = "identity") + ggtitle("Black Mirror")

```

```{r}

media.temporada.f <- dados %>%
  filter(series_name== "Flash") %>%
  group_by(season) %>%
  summarise(media = mean(UserRating))

ggplot(data = media.temporada.f, aes(x=season, y=media, fill = season)) + geom_bar(stat = "identity") + ggtitle("Flash")

```




```{r}
media.geral <- dados %>% filter(series_name %in% c("Arrow", "Vikings", "Breaking Bad", "House of Cards"))

media.geral %>%
  ggplot(aes(x=series,y=UserRating,col=series_name)) +
  geom_point() +
  facet_wrap(~media.geral$series_name,scales = "free_x") +
  xlab("N? do Epis?dio") + ylab("Avalia??o do Usu?rio") +
  labs(col = "S?ries") +
  theme_minimal()

```
